# Generated by Django 2.2.24 on 2021-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0041_auto_20201030_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='action_time',
            field=models.DateTimeField(verbose_name='Date and time nest removal'),
        ),
        migrations.AlterField(
            model_name='managementaction',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Time on site (in minutes)'),
        ),
    ]
