# Generated by Django 2.2.24 on 2021-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0042_auto_20210709_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='site',
            field=models.CharField(blank=True, choices=[('O_NC_B', 'Outside, not covered on building'), ('O_NC_T', 'Outside, not covered in tree or bush'), ('O_C_C', 'Outside, covered by construction'), ('O_N_C', 'Outside, naturally covered'), ('I', 'Inside, in building or construction'), ('UK', 'Unknown')], max_length=7, verbose_name='Nest site'),
        ),
    ]
