# Generated by Django 2.2.24 on 2021-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0042_auto_20210625_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='nest_type',
            field=models.CharField(blank=True, choices=[('AE', 'Active embryo'), ('AP', 'Active primary'), ('AS', 'Active secondary'), ('IE', 'Inactive/empty nest'), ('UK', 'Unknown')], max_length=2, verbose_name='Nest type'),
        ),
    ]
