# Generated by Django 2.2.24 on 2021-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0044_managementaction_aftercare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementActionProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('description_nl', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('description_fr', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('display_order', models.IntegerField(unique=True, verbose_name='Order')),
            ],
        ),
        migrations.AddField(
            model_name='managementaction',
            name='problems',
            field=models.ManyToManyField(blank=True, to='vespawatch.ManagementActionProblem'),
        ),
    ]
