# Generated by Django 2.2.24 on 2021-08-23 09:13

PROBLEMS = (
    # (Order, EN, NL, FR)
    (1, 'None',             'Geen',                         'Aucun'),
    (2, 'Stitches',         'Steken',                       'Points'),
    (3, 'Nest fell down',   'Nest gevallen',                'Chute du nid'),
    (4, 'Dizziness',        'Duizeligheid/misselijkheid',   'Vertige'),
    (5, 'Poison projection','Gif projectie',                'Projection de poison'),
    (6, 'Unknown',          'Ongekend',                     'Inconnu')
)

from django.db import migrations

def delete_problems(apps, schema_editor):
    ProblemModel = apps.get_model('vespawatch', 'ManagementActionProblem')

    for problem in PROBLEMS:
        try:
            ProblemModel.objects.get(description_en=problem[1]).delete()
        except ProblemModel.DoesNotExist:
            pass


def create_problems(apps, schema_editor):
    ProblemModel = apps.get_model('vespawatch', 'ManagementActionProblem')

    for problem in PROBLEMS:
        ProblemModel.objects.create(
            display_order=problem[0],
            description_en=problem[1],
            description_nl=problem[2],
            description_fr=problem[3]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0045_auto_20210823_1112'),
    ]

    operations = [
        migrations.RunPython(create_problems, delete_problems),
    ]
