# Generated by Django 2.2.24 on 2021-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0046_populate_action_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='product',
            field=models.CharField(choices=[('PD', 'Permas-D'), ('LN', 'Liquid nitrogen'), ('V', 'Vespa'), ('FD', 'Ficam D'), ('TP', 'Topscore PAL'), ('EE', 'Ether / acetone / ethyl acetate'), ('DE', 'Diatomaceous earth'), ('O', 'Other'), ('N', 'None'), ('UK', 'Unknown')], default='UK', max_length=3, verbose_name='Product'),
        ),
    ]
