# Generated by Django 2.2.24 on 2021-08-23 13:14

from django.db import migrations


def populate_actions_product(apps, schema_editor):
    ManagementAction = apps.get_model('vespawatch', 'ManagementAction')
    for action in ManagementAction.objects.all():
        outcome = action.outcome

        # !! Models constants not available, so we have to copy/paste values here.
        if outcome == 'PP':  # PERMAS_D_PROF:
            product = 'PD'  # PRODUCT_PERMAS_D
        elif outcome == 'PC':  # PERMAS_D_CLASSIC
            product = 'PD'  # PRODUCT_PERMAS_D
        elif outcome == 'FD':  # REMOVAL_COMPLETE
            product = 'UK'  # PRODUCT_UNKNOWN
        elif outcome ==  'PD':  # REMOVAL_PARTIAL:
            product = 'UK'
        elif outcome == 'ND': # NOT_TREATED:
            product = 'N'  # PRODUCT_NONE
        else:  # 'unknown'
            product = 'UK'

        action.product = product
        action.save(update_fields=['product'])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0047_managementaction_product'),
    ]

    operations = [
        migrations.RunPython(populate_actions_product, do_nothing),
    ]
