# Generated by Django 2.2.24 on 2021-08-23 14:54

from django.db import migrations


def populate_actions_method(apps, schema_editor):
    ManagementAction = apps.get_model('vespawatch', 'ManagementAction')
    for action in ManagementAction.objects.all():
        outcome = action.outcome

        # !! Models constants not available, so we have to copy/paste values here.
        if outcome == 'PP':  # PERMAS_D_PROF:
            method = 'PD'  # Powder distributor
        elif outcome == 'PC':  # PERMAS_D_CLASSIC
            method = 'PD'  # Powder distributor
        elif outcome == 'FD':  # REMOVAL_COMPLETE
            method = 'UK'  # Unknown
        elif outcome == 'PD':  # REMOVAL_PARTIAL:
            method = 'UK'
        elif outcome == 'ND': # NOT_TREATED:
            method = 'NNT'  # PRODUCT_NONE
        else:  # 'unknown'
            method = 'UK'

        action.method = method
        action.save(update_fields=['method'])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0049_managementaction_method'),
    ]

    operations = [
        migrations.RunPython(populate_actions_method, do_nothing),
    ]
