# Generated by Django 2.2.24 on 2021-08-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0050_populate_method_existing_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementaction',
            old_name='outcome',
            new_name='old_outcome',
        ),
    ]
