# Generated by Django 2.2.24 on 2021-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0051_auto_20210824_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='old_outcome',
            field=models.CharField(choices=[('PP', 'Professional permas-D treatment'), ('PC', 'Classic permas-D treatment'), ('FD', 'Complete manual removal'), ('PD', 'Partial manual removal'), ('ND', 'Not treated'), ('UK', 'Unknown')], max_length=2, verbose_name='Outcome (old)'),
        ),
    ]
