# Generated by Django 2.2.24 on 2021-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0054_populate_result_existing_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='result',
            field=models.CharField(choices=[('ST', 'Successfully treated'), ('UT', 'Unsuccessfully treated'), ('UN', 'Untreated'), ('UK', 'Unknown')], default='UK', max_length=3, verbose_name='Result'),
        ),
    ]
