# Generated by Django 2.2.24 on 2021-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0055_auto_20210824_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='nest_reported_before',
            field=models.BooleanField(blank=True, null=True, verbose_name='This nest been reported before'),
        ),
    ]
