# Generated by Django 2.2.24 on 2021-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0056_managementaction_nest_reported_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='file_number_nest_removal',
            field=models.CharField(blank=True, max_length=75, verbose_name='File number nest removal'),
        ),
    ]
