# Generated by Django 2.2.24 on 2021-08-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0057_managementaction_file_number_nest_removal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementaction',
            name='old_outcome',
        ),
    ]
