# Generated by Django 2.2.24 on 2021-08-26 14:19


PROBLEMS = (
    # (Order, EN, NL, FR)
    (1, 'None',             'Geen',                         'Aucun'),
    (2, 'Stitches',         'Steken',                       'Points'),
    (3, 'Nest fell down',   'Nest gevallen',                'Chute du nid'),
    (4, 'Dizziness',        'Duizeligheid/misselijkheid',   'Vertige'),
    (5, 'Poison projection','Gif projectie',                'Projection de poison'),
    (6, 'Unknown',          'Ongekend',                     'Inconnu')
)

from django.db import migrations


def fix_typo(apps, schema_editor):
    ProblemModel = apps.get_model('vespawatch', 'ManagementActionProblem')

    p = ProblemModel.objects.get(description_en='Stitches')
    p.description_en = 'Stings'
    p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0058_remove_managementaction_old_outcome'),
    ]

    operations = [
        migrations.RunPython(fix_typo, lambda: None)
    ]
