# Generated by Django 2.2.24 on 2022-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vespawatch', '0059_fix_typo_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementaction',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time nest removal'),
        ),
    ]
