remote_theme: "mmistakes/so-simple-theme"
title: "Vespa-Watch"
description: "Monitoring of Vespa velutina"
logo: "/images/logo_vespa.jpg"


footer_links:
  - title: Twitter
    url: https://twitter.com/LifeWatchINBO
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/inbo
    icon: fab fa-github-square
copyright: "Made by LifewatchINBO, powered by Jekyll & So Simple. Logo by Danel Solabarrieta, cc-by-sa-2.0"
